export const stories = [{
    title: 'The Ghost Twins’ Matrix Baking Adventure',
    author: 'Joe Chase',
    content: 'In the heart of the Matrix, the Ghost Twins decided to take a break from their usual [noun] and try something new: baking a German chocolate cake. They gathered all the [plural noun] they needed and put on their [adjective] aprons, which were as sleek as their usual attire.  As they started mixing the [noun] and [noun], one twin said, “This is more complicated than hacking into the [noun] mainframe.” The other twin nodded in agreement, carefully measuring out the [noun] with the precision of a [Matrix - related noun].  Just as they were about to pour the batter into the[noun], they realized they had forgotten the [noun]. “We need to be more [adjective],” one twin said, phasing through the [place] to get it.  With all the ingredients finally in place, they put the cake in the [noun] and set the timer for [number] minutes.  While waiting, they decided to [verb] to pass the time, practicing their [Matrix - related skill]. “This is almost as fun as dodging [plural noun],” one twin remarked.  When the timer went off, they carefully took the cake out of the [noun] and admired their work. “It is as [adjective] as a [Matrix- related noun],” one twin said proudly.They added the finishing touches with [noun] and [noun], making it look even more delicious.   Finally, they sat down to enjoy their creation. “This is the best[noun] we have ever made,” one twin said with a [adjective] smile.The other twin agreed, taking a big bite and savoring the [adjective] flavor, knowing that even in the Matrix, they could create something truly special.',
},
{
    title: 'A Prescription for Chaos',
    author: 'Sam Nash',
    content: 'Samuel Nash went to see Dr. [Name]. Samuel came to the doctor because he was struggling with too much [liquid] in his [body part]. The doctor listened to his [body part] with her [instrument] and then told him he needed to take [Number] grams of [medicine] by [route of administration]. She also recommended that he eat more [food] and drink plenty of [liquid]. Sam said, "That does not sound quite right" but the doctor said, "Shut up you little bitch, you will do as I say.I did not spend 1 year in residency at the Medical College of [country] for you to tell me how to be a [Medical Specialty].You obviously need a stat [medical procedure]." After the procedure, Sam was cured and said, "Wow, I have never felt so [adjective] in my whole life.Thank you doc, now I can get back to my life and pursue my true passion of [hobby]."',
},
{
    title: 'Trick-or-Treat Trouble at the Spooky House',
    author: 'Shaun Miller',
    content: '"I was worried my Halloween was off to a [adjective] start when a [color] [creature] crossed my path, but it turned out ok. My best friend the [occupation] and I went trick-or-treating the minute it started getting dark. I dressed as a [adjective] [noun] and my friend was a [adjective] [number] place [noun]. The first few houses gave out their traditional [fruit] instead of candy. When we reached the end of the block, my friend dared me to ring the doorbell on the [adjective] house at the top of the [noun]. I tip-toed to the door and just when I was going to push the button a [description] [creature] answered the door. I screamed and tried to [verb] it until I realized it was just a mask. The old [person] behind the mask gave me three [noun] since she did not have many visitors!"',
},
{
    title: 'A Mysterious Creature and a Missing Friend',
    author: 'Shaun Miller',
    content: "Today I heard a [adjective] noise under the [furniture] cushion and was surprised to find a [creature] hiding in the [location] out back. I screamed, '[phrase]' as I took a curious [number] steps towards it. The [creature] was [color] and almost resembled a [adjective] [noun]. I quickly called my friend that does overnight security at an [adjective] [place] for help because they had a [adjective] [creature] earlier this year -- but they never answered their phone. When I looked up again, the [creature] was gone. It must have fled to [place]!",
},
{
    title: 'A Night of Frights in the Haunted Cellar',
    author: 'Shaun Miller',
    content: "Every year, my [plural noun] take me to a [adjective] House. As I walked down the [adjective] steps to the [location], my head brushed up against a [noun] in the corner. The first room wasn't scary at all. The [noun] [verb] as I walked. A [color] [animal] with its [color] eyes glared at me as it ran across the room. '[phrase]', I said to myself. 'This isn't so bad!' We walked into the next room and there was a [adjective] [noun] on the wall. The [noun]'s eyes in the picture were a ridiculous [color]. I looked over toward the [adjective] window and saw [plural noun] and [plural noun] in jars on the shelf. When I looked back at the [noun], the [noun] was staring at me! Its eyes had changed colors and were now [color]. That's when the lights in the [noun] flickered on and off. I looked to the center of the room where a [color] [noun] of [liquid] was bubbling. A [body part] came slowly out of the [noun] and [verb] its fingers. [plural noun] came [verb] toward me out of the darkness. I had had enough! I was so spooked that I screamed out of the building and up the steps. I decided to wait for my [plural noun] outside. What I didn't realize was that I had wandered into the [place] next door. I looked up at the [celestial body] and saw what appeared to be [number] [plural noun] sharing a [clothing item] flying on a [vehicle].",
},
];
